In [2]:
import numpy as np
import torch

In [2]:
# split into list
inp = "python main.py play --scenario coin-heaven --agents first_agent --n-rounds 10000 --train 1 --no-gui"
inp = inp.split(" ")
for i in inp:
    print('"'+i+'",')

"python",
"main.py",
"play",
"--scenario",
"coin-heaven",
"--agents",
"first_agent",
"--n-rounds",
"10000",
"--train",
"1",
"--no-gui",


In [3]:
# split into list
inp = "play --scenario coin-heaven --agents first_agent --n-rounds 1 --train 1"
inp = inp.split(" ")
for i in inp:
    print('"'+i+'",')

"play",
"--scenario",
"coin-heaven",
"--agents",
"first_agent",
"--n-rounds",
"1",
"--train",
"1",


In [70]:
# split into list
inp = "play --scenario coin-heaven --agents first_agent --n-rounds 10000 --train 1 --no-gui"
inp = inp.split(" ")
for i in inp:
    print('"'+i+'",')


"play",
"--scenario",
"coin-heaven",
"--agents",
"first_agent",
"--n-rounds",
"10000",
"--train",
"1",
"--no-gui",


In [4]:

empty_field =     np.array(    [
            [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
            [-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1],
            [-1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1],
            [-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1],
            [-1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1],
            [-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1],
            [-1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1],
            [-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1],
            [-1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1],
            [-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1],
            [-1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1],
            [-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1],
            [-1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1],
            [-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1],
            [-1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1],
            [-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1],
            [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
        ])

In [7]:
active_indices = empty_field == 0
print(active_indices.astype(int))
print(active_indices.sum())
print(active_indices)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
176
[[False False False False False False False False False False False False
  False False False False False]
 [False  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True False]
 [False  True False  True False  True False  True False  True False  True
  False  True False  True False]
 [False  True  True  True  True  True  True  

In [9]:
empty_field[active_indices.astype(int)].shape

(17, 17, 17)

In [6]:
# can we assign tubles into arrays?
a=np.full((8,),-1)
a[0:2] = (3,4)
a
# YES!

array([ 3,  4, -1, -1, -1, -1, -1, -1])

In [1]:
# testing out deque behavior
from collections import deque

q= deque(maxlen=5)
for i in range(8):
    q.append(i)
q

deque([3, 4, 5, 6, 7], maxlen=5)

In [ ]:
#  this list:ACTIONS = ["UP", "RIGHT", "DOWN", "LEFT", "WAIT", "BOMB"]

In [69]:
import torch
a=torch.tensor(range(12),dtype=torch.float32).reshape((4,3))
print(a)
a[1]=torch.full((3,),torch.nan)
print(a)

b = torch.tensor([2,1,0,1])
c = a.gather(1,b.unsqueeze(1))
c

a.max(dim=1,).values

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
tensor([[ 0.,  1.,  2.],
        [nan, nan, nan],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])


tensor([ 2., nan,  8., 11.])

In [6]:
torch.tensor([(torch.nan * 0)]) .nan_to_num(0.0)

tensor([0.])